eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9999
spring:
  application:
    name: orderservice
  zipkin:
    base-url: http://localhost:8888
feign:
  hystrix:
    enabled: true