eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9997
spring:
  application:
    name: myzuul
  zipkin:
    base-url: http://localhost:8888
zuul:
  routes:
    orderService:
      path: /api-a/**
      serviceId: orderservice
    randomservice2:
      path: /api-b/**
      serviceId: randomservice