eureka:
  client:
    serviceUrl:
#      defaultZone: http://35.220.223.122:8761//eureka/
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9998
spring:
  application:
    name: randomservice